version: "3.9"

services:
  api-release:
    build:
      context: .
      dockerfile: docker/Dockerfile.release
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskdb
    depends_on:
      - db

  api-debug:
    build:
      context: .
      dockerfile: docker/Dockerfile.debug
    ports:
      - "8080:8080"
      - "2345:2345"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskdb
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
